export interface Model2Item {
  model1Id: number;
  supplier: string;

  model2Id: number;
  date: Date;
  issueVocNo: string;
  voucherNumber: string;
  transType: string;
  requestingUnit: string;
  issuingStore: string;
  model: string;
  registeredBy: string;
  status: string;
  category: string;
  stockNumber: string;
  description: string;
  unitOfMeasurment: string;
  onHand: number;
  request: number;
  issued: number;
  // dO : number;
  unitPrice: number;
  totalPrice: number;
  vat: number;
  grandTotal: number;
  preparedBy: string;
  pRank: string;
  pTitle: string;
  checkedBy: string;
  cRank: string;
  cTitle: string;
  approvedBy: string;
  aRank: string;
  aTitle: string;
  issuedTurnBy: string;
  iRank: string;
  iTitle: string;
  issBy: string;
  isRank: string;
  isTitle: string;
  receivedBy: string;
  rRank: string;
  rTitle: string;
  currency: string;
  do: number;
  accessories?: { name: string, quantity: number }[];
  extraItems?: { name: string, quantity: number, store: string, extraStatus: string, extraIssuedByName: string }[];
}
