// // src/app/mock-data.ts
import { Item } from './models/item.model';

export const MOCK_SENT_TO_STORE_ITEMS: Item[] = []
//   {
//     Model1Id: 6,
//     Supplier: 'Supplier F',
//     Category: 'Electronics',
//     PRNO: 'PR006',
//     Date: new Date('2023-10-06'),
//     InvoiceNo: 'INV006',
//     ItemType: 'Tablet',
//     ContactNumber: '2222222222',
//     Number: '1006',
//     RegisteredBy: 'Sarah',
//     SerialNumber: 'SN567890',
//     Description: '10-inch Tablet',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 150,
//     Location: 'Store 1',
//     Remark: 'Sent to Store',
//     Quantity: 10,
//     UnitPrice: 150,
//     TotalPrice: 1500,
//     Currency: 'USD',
//     Manufacturer: 'Samsung',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-06'),
//     BatchNumber: 'BATCH006',
//     checkedByName: 'Tom',
//     ReceivedByName: 'Uma',
//     AuthorizedByName: 'Victor',
//     DateSentToStore: new Date('2023-10-07'),
//     Store: 'Store 1',
//   },
// ];
export const MOCK_SENT_FOR_INSPECTION_ITEMS: Item[] = []
//   {
//     Model1Id: 3,
//     Supplier: 'Supplier C',
//     Category: 'Electronics',
//     PRNO: 'PR003',
//     Date: new Date('2023-10-03'),
//     InvoiceNo: 'INV003',
//     ItemType: 'Monitor',
//     ContactNumber: '5555555555',
//     Number: '1003',
//     RegisteredBy: 'Grace',
//     SerialNumber: 'SN789012',
//     Description: '27-inch Monitor',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'Refurbished',
//     UnitOfPrice: "Birr",
//     Amount: 300,
//     Location: 'Inspection Unit',
//     Remark: 'Pending Inspection',
//     Quantity: 2,
//     UnitPrice: 300,
//     TotalPrice: 600,
//     Currency: 'USD',
//     Manufacturer: 'LG',
//     Warranty: '6 Months',
//     ExpiryDate: new Date('2024-04-03'),
//     BatchNumber: 'BATCH003',
//     checkedByName: 'Henry',
//     ReceivedByName: 'Ivy',
//     AuthorizedByName: 'Jack',
//     DateSentForInspection: new Date('2023-10-03'),
//     Status: 'Pending',
//   },
//   {
//     Model1Id: 4,
//     Supplier: 'Supplier D',
//     Category: 'Furniture',
//     PRNO: 'PR004',
//     Date: new Date('2023-10-04'),
//     InvoiceNo: 'INV004',
//     ItemType: 'Desk',
//     ContactNumber: '4444444444',
//     Number: '1004',
//     RegisteredBy: 'Karen',
//     SerialNumber: 'SN345678',
//     Description: 'Adjustable Standing Desk',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 400,
//     Location: 'Inspection Unit',
//     Remark: 'Pending Inspection',
//     Quantity: 3,
//     UnitPrice: 400,
//     TotalPrice: 1200,
//     Currency: 'USD',
//     Manufacturer: 'IKEA',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-04'),
//     BatchNumber: 'BATCH004',
//     checkedByName: 'Liam',
//     ReceivedByName: 'Mia',
//     AuthorizedByName: 'Noah',
//     DateSentForInspection: new Date('2023-10-04'),
//     Status: 'Pending',
//   },
// ];

export const MOCK_NOTIFICATIONS: Item[] = []
//   {

//     Model1Id: 7,
//     Supplier: 'Supplier G',
//     Category: 'Electronics',
//     PRNO: 'PR007',
//     Date: new Date('2023-10-07'),
//     InvoiceNo: 'INV007',
//     ItemType: 'Smartphone',
//     ContactNumber: '1111111111',
//     Number: '1007',
//     RegisteredBy: 'Wendy',
//     SerialNumber: 'SN123789',
//     Description: '5G Smartphone',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 800,
//     Location: 'Inspection Unit',
//     Remark: 'Received by Inspection Unit',
//     Quantity: 1,
//     UnitPrice: 800,
//     TotalPrice: 800,
//     Currency: 'USD',
//     Manufacturer: 'Apple',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-07'),
//     BatchNumber: 'BATCH007',
//     checkedByName: 'Xander',
//     ReceivedByName: 'Yara',
//     AuthorizedByName: 'Zack',
//     DateReceivedByInspection: new Date('2023-10-08'),
//     Status: 'Received by Inspection Unit',
//   },
// ];

export const MOCK_RECEIVED_ITEMS: Item[] = []
//   {
//     Model1Id: 1,
//     Supplier: 'Supplier V',
//     Category: 'Electronics',
//     PRNO: 'PR001',
//     Date: new Date('2023-10-01'),
//     InvoiceNo: 'INV001',
//     ItemType: 'Laptop',
//     ContactNumber: '1234567890',
//     Number: '1001',
//     RegisteredBy: 'John Doe',
//     SerialNumber: 'SN123456',
//     Description: '15-inch Laptop',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 1200,
//     Location: 'Warehouse 1',
//     Remark: 'Urgent',
//     Quantity: 1,
//     UnitPrice: 1200,
//     TotalPrice: 1200,
//     Currency: 'USD',
//     Manufacturer: 'Dell',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-01'),
//     BatchNumber: 'BATCH001',
//     checkedByName: 'Alice',
//     ReceivedByName: 'Bob',
//     AuthorizedByName: 'Charlie',
//     Status: 'Pending Inspection',
//   },
//   {
//     Model1Id: 2,
//     Supplier: 'Supplier B',
//     Category: 'Furniture',
//     PRNO: 'PR002',
//     Date: new Date('2023-10-02'),
//     InvoiceNo: 'INV002',
//     ItemType: 'Office Chair',
//     ContactNumber: '9876543210',
//     Number: '1002',
//     RegisteredBy: 'Jane Doe',
//     SerialNumber: 'SN654321',
//     Description: 'Ergonomic Office Chair',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 200,
//     Location: 'Warehouse 2',
//     Remark: 'Standard',
//     Quantity: 5,
//     UnitPrice: 200,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'Herman Miller',
//     Warranty: '2 Years',
//     ExpiryDate: new Date('2025-10-02'),
//     BatchNumber: 'BATCH002',
//     checkedByName: 'David',
//     ReceivedByName: 'Eva',
//     AuthorizedByName: 'Frank',
//     Status: 'Pending Inspection',
//   },
//   {
//     Model1Id: 3,
//     Supplier: 'Supplier C',
//     Category: 'Electronics',
//     PRNO: 'PR001',
//     Date: new Date('2023-10-01'),
//     InvoiceNo: 'INV001',
//     ItemType: 'Laptop',
//     ContactNumber: '1234567890',
//     Number: '1001',
//     RegisteredBy: 'John Doe',
//     SerialNumber: 'SN123456',
//     Description: '15-inch Laptop',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 1200,
//     Location: 'Warehouse 1',
//     Remark: 'Urgent',
//     Quantity: 1,
//     UnitPrice: 1200,
//     TotalPrice: 1200,
//     Currency: 'USD',
//     Manufacturer: 'Dell',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-01'),
//     BatchNumber: 'BATCH001',
//     checkedByName: 'Alice',
//     ReceivedByName: 'Bob',
//     AuthorizedByName: 'Charlie',
//     Status: 'Pending Inspection',
//   },
//   {
//     Model1Id: 4,
//     Supplier: 'Supplier D',
//     Category: 'Furniture',
//     PRNO: 'PR002',
//     Date: new Date('2023-10-02'),
//     InvoiceNo: 'INV002',
//     ItemType: 'Office Chair',
//     ContactNumber: '9876543210',
//     Number: '1002',
//     RegisteredBy: 'Jane Doe',
//     SerialNumber: 'SN654321',
//     Description: 'Ergonomic Office Chair',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 200,
//     Location: 'Warehouse 2',
//     Remark: 'Standard',
//     Quantity: 5,
//     UnitPrice: 200,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'Herman Miller',
//     Warranty: '2 Years',
//     ExpiryDate: new Date('2025-10-02'),
//     BatchNumber: 'BATCH002',
//     checkedByName: 'David',
//     ReceivedByName: 'Eva',
//     AuthorizedByName: 'Frank',
//     Status: 'Approved',
//   },
//   {
//     Model1Id: 5,
//     Supplier: 'Supplier E',
//     Category: 'Electronics',
//     PRNO: 'PR001',
//     Date: new Date('2023-10-01'),
//     InvoiceNo: 'INV001',
//     ItemType: 'Laptop',
//     ContactNumber: '1234567890',
//     Number: '1001',
//     RegisteredBy: 'John Doe',
//     SerialNumber: 'SN123456',
//     Description: '15-inch Laptop',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 1200,
//     Location: 'Warehouse 1',
//     Remark: 'Urgent',
//     Quantity: 1,
//     UnitPrice: 1200,
//     TotalPrice: 1200,
//     Currency: 'USD',
//     Manufacturer: 'Dell',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-01'),
//     BatchNumber: 'BATCH001',
//     checkedByName: 'Alice',
//     ReceivedByName: 'Bob',
//     AuthorizedByName: 'Charlie',
//     Status: 'Approved',
//   },
//   {
//     Model1Id: 6,
//     Supplier: 'Supplier F',
//     Category: 'Furniture',
//     PRNO: 'PR002',
//     Date: new Date('2023-10-02'),
//     InvoiceNo: 'INV002',
//     ItemType: 'Office Chair',
//     ContactNumber: '9876543210',
//     Number: '1002',
//     RegisteredBy: 'Jane Doe',
//     SerialNumber: 'SN654321',
//     Description: 'Ergonomic Office Chair',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 200,
//     Location: 'Warehouse 2',
//     Remark: 'Standard',
//     Quantity: 5,
//     UnitPrice: 200,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'Herman Miller',
//     Warranty: '2 Years',
//     ExpiryDate: new Date('2025-10-02'),
//     BatchNumber: 'BATCH002',
//     checkedByName: 'David',
//     ReceivedByName: 'Eva',
//     AuthorizedByName: 'Frank',
//     Status: 'Approved',
//   },
//   {
//     Model1Id: 7,
//     Supplier: 'Supplier G',
//     Category: 'Electronics',
//     PRNO: 'PR001',
//     Date: new Date('2023-10-01'),
//     InvoiceNo: 'INV001',
//     ItemType: 'Laptop',
//     ContactNumber: '1234567890',
//     Number: '1001',
//     RegisteredBy: 'John Doe',
//     SerialNumber: 'SN123456',
//     Description: '15-inch Laptop',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 1200,
//     Location: 'Warehouse 1',
//     Remark: 'Urgent',
//     Quantity: 1,
//     UnitPrice: 1200,
//     TotalPrice: 1200,
//     Currency: 'USD',
//     Manufacturer: 'Dell',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-01'),
//     BatchNumber: 'BATCH001',
//     checkedByName: 'Alice',
//     ReceivedByName: 'Bob',
//     AuthorizedByName: 'Charlie',
//     Status: 'Approved',
//   },
//   {
//     Model1Id: 8,
//     Supplier: 'Supplier H',
//     Category: 'Furniture',
//     PRNO: 'PR002',
//     Date: new Date('2023-10-02'),
//     InvoiceNo: 'INV002',
//     ItemType: 'Office Chair',
//     ContactNumber: '9876543210',
//     Number: '1002',
//     RegisteredBy: 'Jane Doe',
//     SerialNumber: 'SN654321',
//     Description: 'Ergonomic Office Chair',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 200,
//     Location: 'Warehouse 2',
//     Remark: 'Standard',
//     Quantity: 5,
//     UnitPrice: 200,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'Herman Miller',
//     Warranty: '2 Years',
//     ExpiryDate: new Date('2025-10-02'),
//     BatchNumber: 'BATCH002',
//     checkedByName: 'David',
//     ReceivedByName: 'Eva',
//     AuthorizedByName: 'Frank',
//     Status: 'Approved',
//   },
//   {
//     Model1Id: 9,
//     Supplier: 'Supplier I',
//     Category: 'Electronics',
//     PRNO: 'PR001',
//     Date: new Date('2023-10-01'),
//     InvoiceNo: 'INV001',
//     ItemType: 'Laptop',
//     ContactNumber: '1234567890',
//     Number: '1001',
//     RegisteredBy: 'John Doe',
//     SerialNumber: 'SN123456',
//     Description: '15-inch Laptop',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 1200,
//     Location: 'Warehouse 1',
//     Remark: 'Urgent',
//     Quantity: 1,
//     UnitPrice: 1200,
//     TotalPrice: 1200,
//     Currency: 'USD',
//     Manufacturer: 'Dell',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-01'),
//     BatchNumber: 'BATCH001',
//     checkedByName: 'Alice',
//     ReceivedByName: 'Bob',
//     AuthorizedByName: 'Charlie',
//     Status: 'Approved',
//   },
//   {
//     Model1Id: 10,
//     Supplier: 'Supplier J',
//     Category: 'Furniture',
//     PRNO: 'PR002',
//     Date: new Date('2023-10-02'),
//     InvoiceNo: 'INV002',
//     ItemType: 'Office Chair',
//     ContactNumber: '9876543210',
//     Number: '1002',
//     RegisteredBy: 'Jane Doe',
//     SerialNumber: 'SN654321',
//     Description: 'Ergonomic Office Chair',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 200,
//     Location: 'Warehouse 2',
//     Remark: 'Standard',
//     Quantity: 5,
//     UnitPrice: 200,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'Herman Miller',
//     Warranty: '2 Years',
//     ExpiryDate: new Date('2025-10-02'),
//     BatchNumber: 'BATCH002',
//     checkedByName: 'David',
//     ReceivedByName: 'Eva',
//     AuthorizedByName: 'Frank',
//     Status: 'Approved',
//   },
// ];

export const MOCK_INSPECTED_ITEMS: Item[] = []
//   {
//     Model1Id: 5,
//     Supplier: 'Supplier E',
//     Category: 'Electronics',
//     PRNO: 'PR005',
//     Date: new Date('2023-10-05'),
//     InvoiceNo: 'INV005',
//     ItemType: 'Printer',
//     ContactNumber: '3333333333',
//     Number: '1005',
//     RegisteredBy: 'Olivia',
//     SerialNumber: 'SN901234',
//     Description: 'Laser Printer',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 250,
//     Location: 'Warehouse 1',
//     Remark: 'Inspected and Approved',
//     Quantity: 4,
//     UnitPrice: 250,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'HP',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-05'),
//     BatchNumber: 'BATCH005',
//     checkedByName: 'Peter',
//     ReceivedByName: 'Quinn',
//     AuthorizedByName: 'Rachel',
//     DateSentForInspection: new Date('2023-10-05'),
//     DateReceivedByInspection: new Date('2023-10-06'),
//     Status: 'Approved',
//   },

//   {
//     Model1Id: 5,
//     Supplier: 'Supplier V',
//     Category: 'Electronics',
//     PRNO: 'PR005',
//     Date: new Date('2023-10-05'),
//     InvoiceNo: 'INV005',
//     ItemType: 'የረጅም ርቀት ራዲዮ',
//     ContactNumber: '3333333333',
//     Number: '1005',
//     RegisteredBy: 'Olivia',
//     SerialNumber: 'SN901234',
//     Description: 'Laser Printer',
//     UnitOfMeasurment: 'Piece',
//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 250,
//     Location: 'Warehouse 1',
//     Remark: 'Inspected and Approved',
//     Quantity: 4,
//     UnitPrice: 250,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'HP',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-05'),
//     BatchNumber: 'BATCH005',
//     checkedByName: 'Peter',
//     ReceivedByName: 'Quinn',
//     AuthorizedByName: 'Rachel',
//     DateSentForInspection: new Date('2023-10-05'),
//     DateReceivedByInspection: new Date('2023-10-06'),
//     Status: 'Approved',
//   },

//   {
//     Model1Id: 5,
//     Supplier: 'Supplier F',
//     Category: 'Electronics',
//     PRNO: 'PR005',
//     Date: new Date('2023-10-05'),
//     InvoiceNo: 'INV005',
//     ItemType: 'Laptop',
//     ContactNumber: '3333333333',
//     Number: '1005',
//     RegisteredBy: 'Olivia',
//     SerialNumber: 'SN901234',
//     Description: 'Laser Printer',
//     UnitOfMeasurment: 'Piece',

//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 250,
//     Location: 'Warehouse 1',
//     Remark: 'Inspected and Approved',
//     Quantity: 4,
//     UnitPrice: 250,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'HP',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-05'),
//     BatchNumber: 'BATCH005',
//     checkedByName: 'Peter',
//     ReceivedByName: 'Quinn',
//     AuthorizedByName: 'Rachel',
//     DateSentForInspection: new Date('2023-10-05'),
//     DateReceivedByInspection: new Date('2023-10-06'),
//     Status: 'Approved',
//   },

//   {
//     Model1Id: 5,
//     Supplier: 'Supplier G',
//     Category: 'Electronics',
//     PRNO: 'PR005',
//     Date: new Date('2023-10-05'),
//     InvoiceNo: 'INV005',
//     ItemType: 'Desktop Computer',
//     ContactNumber: '3333333333',
//     Number: '1005',
//     RegisteredBy: 'Olivia',
//     SerialNumber: 'SN901234',
//     Description: 'Laser Printer',
//     UnitOfMeasurment: 'Piece',

//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 250,
//     Location: 'Warehouse 1',
//     Remark: 'Inspected and Approved',

//     Quantity: 4,
//     UnitPrice: 250,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'HP',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-05'),
//     BatchNumber: 'BATCH005',
//     checkedByName: 'Peter',
//     ReceivedByName: 'Quinn',
//     AuthorizedByName: 'Rachel',
//     DateSentForInspection: new Date('2023-10-05'),
//     DateReceivedByInspection: new Date('2023-10-06'),
//     Status: 'Approved',
//   },

//   {
//     model1Id: 5,
//     Supplier: 'Supplier K',
//     Category: 'Electronics',
//     PRNO: 'PR005',
//     Date: new Date('2023-10-05'),
//     InvoiceNo: 'INV005',
//     ItemType: 'Radio',
//     ContactNumber: '3333333333',
//     Number: '1005',
//     RegisteredBy: 'Olivia',
//     SerialNumber: 'SN901234',
//     Description: 'Laser Printer',
//     UnitOfMeasurment: 'Piece',

//     Quality: 'New',
//     UnitOfPrice: "Birr",
//     Amount: 250,
//     Location: 'Warehouse 1',
//     Remark: 'Inspected and Approved',

//     Quantity: 4,
//     UnitPrice: 250,
//     TotalPrice: 1000,
//     Currency: 'USD',
//     Manufacturer: 'HP',
//     Warranty: '1 Year',
//     ExpiryDate: new Date('2024-10-05'),
//     BatchNumber: 'BATCH005',
//     checkedByName: 'Peter',
//     ReceivedByName: 'Quinn',
//     AuthorizedByName: 'Rachel',
//     DateSentForInspection: new Date('2023-10-05'),
//     DateReceivedByInspection: new Date('2023-10-06'),
//     Status: 'Approved',
//   },
// ];
